### ISSUE TITLE
Multinomial responses

### ISSUE THREAD

**Issue by awmercer** [kapelner/bartMachine#14]
bartMachine is fantastic and has much nicer features than the other BART implementations available in R. The one thing it's missing is the capacity to handle multinomial outcomes.  Is that on the roadmap?

**Comment by kapelner** [comment]
Not at the moment. There is a paper that describes how to implement it. I'd
be very happy to accept a pull request though!

**Comment by jbleich89** [comment]
There's also some source C++ code lying around on the author's site (or there was) that could be followed if that's helpful. It mostly requires wrapping the heavy lifting we've already done with an additional BART model per response outcome if I recall.
