### ISSUE TITLE
install hangs on checking Java runtime

### ISSUE THREAD

**Issue by jeffwong-nflx** [kapelner/bartMachine#16]
Hi, the installation I am seeing hangs on

```
checking whether Java run-time works... yes
checking whether -Xrs is supported...
```

I can confirm that I have a JDK installed, and I have done the R CMD javareconf step.  I installed rJava through apt-get install r-cran-rjava. Do you have any tips on what to look for while debugging?

**Comment by kapelner** [comment]
What's your jdk version? The first thing I would do is reinstall java and
install an old version, say the last stable Java 7.
