### ISSUE TITLE
Memory Allocation for bartMachine

### ISSUE THREAD

**Issue by llouis01** [kapelner/bartMachine#41]
Greetings,

I have spent a lot of time researching how to fix the memory issue in bartMachine, but nothing that I have tried has worked.

Interestingly enough, it worked first try last night. Then I saved my script and logged off. Today I went back in, and nothing is working. I have started a new session with no package loaded, ran the "java.prameters" code BEFORE "library(bartMachine)" a few dozen times; nothing works. During some iterations, it works, but then upon repeating the exact same steps that made it work, it failed again. 

I have tried every suggestions here https://stackoverflow.com/questions/34624002/r-error-java-lang-outofmemoryerror-java-heap-space and here https://github.com/kapelner/bartMachine/issues/5 . Is there something that I am missing? My machine has 64GB; I have been allocating up to 50 but nothing seems to work.

Thanks,
Lou

**Comment by kapelner** [comment]
This is definitely a Java / rJava problem. Good luck tracing it down. I've sunk countless hours into that abyss.

**Comment by llouis01** [comment]
That's fine. I just kept running it until it gives me a green light, then I proceed to continuing my analysis. The vignette was really helpful also. Thank you very much! Give a stranger's greetings to Professors Dorian Abreu, Natalia Condolo, and Suleyman T. from me.

Best,
LL

**Comment by llouis01** [comment]
Definitely something to try! Thanks for the tips!
