### ISSUE TITLE
Survival outcome

### ISSUE THREAD

**Issue by aaronxs** [kapelner/bartMachine#43]
Hi there,

Is there any way to analyze survival outcomes using the package currently?

Thanks!

**Comment by kapelner** [comment]
No. Check out https://rdrr.io/rforge/survbart/

**Comment by aaronxs** [comment]
Hi there, 

Thank you so much for suggesting an alternative package to model survival outcomes using BART. 

I was wondering, do you happened to know if there is a way to apply the `interaction_investigator()` function to the object created by the `surv.bart()` ?

Thanks!

**Comment by kapelner** [comment]
It's a different package. So, no.
