### ISSUE TITLE
Exporting CIs

### ISSUE THREAD

**Issue by ecrjak** [kapelner/bartMachine#44]
Hi there. First, thanks a lot for this great package :)

Second, I was wondering if there's a way to save/access the confidence bounds created in the `pd_plot` command? I would like to customise the output in `ggplot` before exporting but `pd_plot` only saves quantiles and posterior means but not the confidence bounds shown in the graph.

Any suggestions would be very welcome. Many thanks in advance!

**Comment by kapelner** [comment]
This was already completed in [previous commit]( https://github.com/kapelner/bartMachine/commit/c04a1e0a5f7386b2f4c73b62ed980527ec4c8f35). Pull from github and install via `ant` then `R CMD INSTALL bartMachine`.
