### ISSUE TITLE
structure in the response variable

### ISSUE THREAD

**Issue by ntromas** [kapelner/bartMachine#45]
Hi, 

This is probably a very naive question but I have multiple datasets from different sites that might have different properties. My response variable and my explanatory var are similar in all datasets. I wonder how it is possible to take into account the sites information.
If I split by sites, I might lose some of them as they have less information than other.

Thanks!

Nico

**Comment by kapelner** [comment]
Maybe code "site" as a categorical variable and rbind all datasets
together.

Github issues are not for basic statistics help. You should've emailed me.
