### ISSUE TITLE
bartMachine doesn't look in its local environment for X and y

### ISSUE THREAD

**Issue by schwa021** [kapelner/bartMachine#47]
Sorry - but I might not be using the terminology correctly. Maybe this is an "R" issue (I'm a user - but not a programming expert). However, this behavior differs from any other function I have used in R (base or packages).

The issue is that when I call **bartMachine(X, y**) from inside of a function, it pulls X and y from the Global environment - not the values of X and y that I passed it.

Here is a reproducible example:

Basically, the first time through I make sure x and y are not present in the global environment. I then check that x and y are present inside my function (i.e., I didn't screw up passing them). But, when bartMachine(x, y) is called, it says it can't find x.

Then I define x and y in the global environment, make the same call, and voila.

library(tidyverse)
library(bartMachine)

data(mtcars)
vlist <- c("cyl", "disp")

testmod <- function(d, t, v){
  x <- d[v]
  y <- d[[t]]
  
  cat("Is x here? Yes - here is x[1,1] ", x[1,1])
  cat("\n")
  cat("Is y here? Yes, here is y[1] ", y[1])
  cat("\n")

  mod <- bartMachine(X = x, y = y)
  
  return(mod)
}

rm(x, y)
#> Warning in rm(x, y): object 'x' not found
#> Warning in rm(x, y): object 'y' not found

modwt <- testmod(mtcars, "wt", vlist)
#> Is x here? Yes - here is x[1,1]  6
#> Is y here? Yes, here is y[1]  2.62
#> bartMachine initializing with 50 trees...
#> Error in (function (X = NULL, y = NULL, Xy = NULL, num_trees = 50, num_burn_in = 250, : object 'x' not found

x <-  mtcars[c("cyl", "disp")]
y <- mtcars[["wt"]]

modwt <- testmod(mtcars, "wt", vlist)
#> Is x here? Yes - here is x[1,1]  6
#> Is y here? Yes, here is y[1]  2.62
#> bartMachine initializing with 50 trees...
#> bartMachine vars checked...
#> bartMachine java init...
#> bartMachine factors created...
#> bartMachine before preprocess...
#> bartMachine after preprocess... 2 total features...
#> bartMachine sigsq estimated...
#> bartMachine training data finalized...
#> Now building bartMachine for regression...
#> evaluating in sample data...done
Created on 2023-02-27 with [reprex v2.0.2](https://reprex.tidyverse.org/)

**Comment by kapelner** [comment]
Sorry... this was my fault. You can now `git pull` and `R CMD INSTALL bartMachine` or just wait for a few days to get the update from CRAN to v1.3.3.1.
