### ISSUE TITLE
Error code when using bartMachine

### ISSUE THREAD

**Issue by alex76347** [kapelner/bartMachine#49]
I have been attempting to create a PS model using bartMachine. My code is as follows:

new_ps_model <- bartMachine(X = data %>%
                                dplyr::select(colnames(bart_ps_model$X)),
                            y = data[,"drugclass"] %>%
                                unlist(),
                            numtrees = 50,
                            use_missing_data = TRUE,
                            num_burn_in = 10,
                            num_iterations_after_burn_in = 10,
                            serialize = FALSE)
When this function runs, I get the following error:

Error in if (xi > xj) 1L else -1L : missing value where TRUE/FALSE needed
In addition: Warning messages:
1: In xtfrm.data.frame(x) : cannot xtfrm data frames
2: In Ops.factor(xi, xj) : '>' not meaningful for factors

Not sure exactly where to go with this - I went through my data and while there are some missing values in the columns in X, there are no missing values in y. Would appreciate any recommendations for next steps.

**Comment by kapelner** [comment]
Do the dplyr manipulation outside and then cast it as a data.frame and then
try.
