### ISSUE TITLE
Java memory using problem

### ISSUE THREAD

**Issue by peorthrind** [kapelner/bartMachine#5]
I ran a BART model with 11000 samples and 20 features(half of them are categorical variable). My mac has 8G ram. At first, I set memory to 5000 MB via function set_bart_machine_memory(5000).

Then I can fit a model through the function bartMachine one time. If I want to run another model then the R returns a error like this:

> Exception in thread "pool-10-thread-1" Exception in thread "pool-10-thread-3" 
> java.lang.OutOfMemoryError: Java heap space
> java.lang.OutOfMemoryError: Java heap space
> Exception in thread "pool-10-thread-2" java.lang.OutOfMemoryError: Java heap space
> Exception in thread "pool-10-thread-4" java.lang.OutOfMemoryError: Java heap space
> 錯誤在.jcall(bart_machine$java_bart_machine, "Z", "isDestroyed") : 
>  java.lang.OutOfMemoryError: Java heap space

I think that having two bartMachine object in memory may not be a good idea, so I just kill the first model through function destroy_bart_machine(), then the second model is OK to run.

The main problem is on bartMachineCV(). There are about 20 model to fit in default, and the memory error like the one above hits me when R is running the bart model with second set of parameter setting (that is : bartMachine CV try: k: 2 nu, q: 3, 0.9 m: 200  ).

Is that the bartMachineCV() function run all the 20 or more model, save all of them in the memory, then pick the "best RMSE performance" one up? I think that will be a problem to computer with limited memory space.

If the bartMachineCV() function can finish the first model, save the RMSE result, then destroy the first bart object in memory, then run the second model..... until all the CV models are finished. Now you have 20 RMSE values, and pick the one has best RMSE, then run THIS BEST MODEL again...... It will take a litter bit more time, but can save a lot of memory space...... Is that a good idea? Or is there some way to run  bartMachineCV() on a 8GB RAM computer?

Thanks.

**Comment by kapelner** [comment]
Did this ever work for you? Can I close?

**Comment by samcarlos** [comment]
Hey I haven't figured the Java issue but since it's not a bartmachine problem you can close it. 

Thanks!
