### ISSUE TITLE
Negative probabilities in posterior for classification problem

### ISSUE THREAD

**Issue by schwa021** [kapelner/bartMachine#53]
I am running a dichotomous classification problem using _bartMachine_.

When I check the posterior (example below) using _bart_machine_get_posterior_ I see some negative values.

![image](https://github.com/kapelner/bartMachine/assets/25011558/eb577e28-8860-47c6-a0e4-a4ed32dd0c69)

According to the help, the units are probabilities (e.g., not probits).

"_y_hat_posterior_samples The full set of posterior samples of size num_iterations_after_burn_in for each observation. For regression, the estimates have the same units as the response. For classification, the estimates are probabilities._"

Thus, negative values should be impossible. Any thoughts regarding what's happening here? It's not an isolated case.

**Comment by kapelner** [comment]
Can you provide a working example with the data?

**Comment by schwa021** [comment]
Issue resolved. Sorry for wasting your time.

As I was working on a reprex I found out that my y-variable had been converted to a number (instead of factor) due to me screwing up something with indirection in Dplyr.

Thanks again for the great package. Can't wait for the multinomial models ;)
