### ISSUE TITLE
bartMachine using more than 100% CPU even with set_bart_machine_num_cores(1)

### ISSUE THREAD

**Issue by rdiaz02** [kapelner/bartMachine#56]
This isn't really a bug, but maybe worth pointing it out in the documentation or the README?

I am running multiple bartMachines in parallel (with package SuperLearner: https://cran.r-project.org/web/packages/SuperLearner/index.html) in a snow cluster. To avoid running more threads than cores I have I was setting `set_bart_machine_num_cores(1)` and yet, top was showing CPU usages per process much larger than 100% (reaching at times 200% or 300%), leading to CPU overloading. 

It turns out that doing `Sys.setenv(JAVA_TOOL_OPTIONS = "-XX:ParallelGCThreads=1")`  in both the master and the slaves (i.e., `clusterEvalQ(your_cluster_name, {Sys.setenv(JAVA_TOOL_OPTIONS = "-XX:ParallelGCThreads=1")})`  seems to fix the issue. (Java ignorant hee, so this was trial and error and googling around).

Leaving it here for anyone else how might stumble upon it. I can create a PR to the README if deemed appropriate.

**Comment by kapelner** [comment]
Nice find! I would love a PR to the readme.

**Comment by rdiaz02** [comment]
Done: https://github.com/kapelner/bartMachine/pull/57

(I wasn't sure where to put the paragraph. Of course, move wherever it feels more appropriate).

**Comment by rdiaz02** [comment]
Thank you! Closing the issue.
