### ISSUE TITLE
Guidance on setting up bartMachine in cloud environment

### ISSUE THREAD

**Issue by njawadekar** [kapelner/bartMachine#58]
I am dealing with a large dataset (> 80,000 observations), and therefore I am not able to run my analyses using bartMachine on my local computer (it keeps saying it's out of memory when I try building a BART model). However, given its Java dependencies, I am finding it overly complex to be able to install and set-up bartMachine in a virtual environment (e.g. Google Cloud Platform). 

Do you think it would be possible to write-up a quick "how-to" for guiding us through the install and set-up of bartMachine in a virtual machine environment, such as via Google Cloud Platform? This would be very helpful for being able to use this package in the cloud.

**Comment by kapelner** [comment]
I reall don't know much about this other than what the setup is currently and setting `options(java.parameters = "-Xmx.....g")` to be as large as possible for the RAM. Also - "issues" are for bugs in the current code (not improvements nor asks).
